import type { FlowNode, FlowEdge, FlowNodeData } from '@/db/schema/flows'

export interface GenerateFlowSpecInput {
  name: string
  nodes: FlowNode[]
  edges: FlowEdge[]
}

/**
 * Generates a Playwright .spec.ts file from a flow graph.
 * Throws if a cycle is detected or a node has >2 outgoing edges.
 * Supports conditional branching: edges with condition 'if_visible' / 'if_not_visible'
 * generate if/else blocks. Max 2 outgoing edges per node.
 */
export function generateFlowSpec(input: GenerateFlowSpecInput): string {
  const { name, nodes, edges } = input

  if (nodes.length === 0) throw new Error('Flow has no nodes')

  // Build adjacency map: nodeId → outgoing edges
  const outgoing = new Map<string, FlowEdge[]>()
  const inDegree = new Map<string, number>()
  for (const n of nodes) {
    outgoing.set(n.id, [])
    inDegree.set(n.id, 0)
  }
  for (const e of edges) {
    outgoing.get(e.source)?.push(e)
    inDegree.set(e.target, (inDegree.get(e.target) ?? 0) + 1)
  }

  // Validate: max 2 outgoing edges per node
  for (const [nodeId, edgeList] of outgoing) {
    if (edgeList.length > 2) {
      const node = nodes.find(n => n.id === nodeId)
      throw new Error(`Node "${node?.data.label ?? nodeId}" has more than 2 outgoing edges. Maximum is 2 (for if/else branching).`)
    }
  }

  // Cycle detection via DFS
  detectCycles(nodes, outgoing)

  // Find root nodes (in-degree = 0)
  const roots = nodes.filter(n => (inDegree.get(n.id) ?? 0) === 0)
  if (roots.length === 0) throw new Error('Flow contains a cycle — no root nodes found')

  const nodeMap = new Map(nodes.map(n => [n.id, n]))
  const now = new Date().toISOString()

  const lines: string[] = []
  lines.push(`// Generated by KayScope — Flow: "${name}"`)
  lines.push(`// Generated at: ${now}`)
  lines.push(`// Nodes: ${nodes.length}`)
  lines.push(``)
  lines.push(`import { test, expect } from '@playwright/test'`)
  lines.push(``)

  // Each connected component from a root = one test block
  for (const root of roots) {
    const testName = roots.length === 1 ? name : `${name} — ${root.data.label}`
    lines.push(`test(${JSON.stringify(testName)}, async ({ page }) => {`)
    const visited = new Set<string>()
    lines.push(...generateNodeCode(root, nodeMap, outgoing, visited, '  '))
    lines.push(`})`)
    lines.push(``)
  }

  return lines.join('\n')
}

function detectCycles(nodes: FlowNode[], outgoing: Map<string, FlowEdge[]>) {
  const WHITE = 0, GRAY = 1, BLACK = 2
  const color = new Map<string, number>(nodes.map(n => [n.id, WHITE]))

  function dfs(nodeId: string) {
    color.set(nodeId, GRAY)
    for (const edge of outgoing.get(nodeId) ?? []) {
      const c = color.get(edge.target)
      if (c === GRAY) throw new Error('Flow contains a cycle')
      if (c === WHITE) dfs(edge.target)
    }
    color.set(nodeId, BLACK)
  }

  for (const n of nodes) {
    if (color.get(n.id) === WHITE) dfs(n.id)
  }
}

function generateNodeCode(
  node: FlowNode,
  nodeMap: Map<string, FlowNode>,
  outgoing: Map<string, FlowEdge[]>,
  visited: Set<string>,
  indent: string
): string[] {
  if (visited.has(node.id)) return []
  visited.add(node.id)

  const lines: string[] = []

  // Emit node action
  lines.push(`${indent}// ${node.data.label}`)
  for (const line of nodeDataToCode(node.data)) {
    lines.push(`${indent}${line}`)
  }

  const edges = outgoing.get(node.id) ?? []

  if (edges.length === 0) {
    // Terminal node
    return lines
  }

  if (edges.length === 1) {
    // Linear continuation
    const next = nodeMap.get(edges[0]!.target)
    if (next && !visited.has(next.id)) {
      lines.push(...generateNodeCode(next, nodeMap, outgoing, visited, indent))
    }
    return lines
  }

  // 2 edges — conditional branching
  const ifEdge = edges.find(e => e.data?.condition === 'if_visible')
    ?? edges.find(e => e.data?.condition !== 'if_not_visible')
    ?? edges[0]!
  const elseEdge = edges.find(e => e !== ifEdge) ?? edges[1]!

  const condText = esc(ifEdge.data?.conditionText ?? ifEdge.label ?? 'element')

  lines.push(`${indent}if (await page.getByText(\`${condText}\`).isVisible()) {`)
  const ifNode = nodeMap.get(ifEdge.target)
  if (ifNode && !visited.has(ifNode.id)) {
    const ifVisited = new Set(visited)
    lines.push(...generateNodeCode(ifNode, nodeMap, outgoing, ifVisited, indent + '  '))
  }
  lines.push(`${indent}} else {`)
  const elseNode = nodeMap.get(elseEdge.target)
  if (elseNode && !visited.has(elseNode.id)) {
    const elseVisited = new Set(visited)
    lines.push(...generateNodeCode(elseNode, nodeMap, outgoing, elseVisited, indent + '  '))
  }
  lines.push(`${indent}}`)

  return lines
}

function nodeDataToCode(d: FlowNodeData): string[] {
  switch (d.type) {
    case 'navigate':
      return [`await page.goto(\`${esc(d.url ?? '')}\`)`]
    case 'click_text':
      return [`await page.getByText(\`${esc(d.text ?? '')}\`).first().click()`]
    case 'click_role':
      return [`await page.getByRole('${d.role ?? 'button'}', { name: \`${esc(d.roleName ?? '')}\` }).click()`]
    case 'click_placeholder':
      return [`await page.getByPlaceholder(\`${esc(d.placeholder ?? '')}\`).click()`]
    case 'click_title':
      return [`await page.getByTitle(\`${esc(d.title ?? '')}\`).click()`]
    case 'hover_text':
      return [`await page.getByText(\`${esc(d.text ?? '')}\`).hover()`]
    case 'fill_placeholder':
      return [`await page.getByPlaceholder(\`${esc(d.placeholder ?? '')}\`).fill(\`${esc(d.value ?? '')}\`)`]
    case 'fill_label':
      return [`await page.getByLabel(\`${esc(d.labelText ?? '')}\`).fill(\`${esc(d.value ?? '')}\`)`]
    case 'select_option':
      return [`await page.getByLabel(\`${esc(d.labelText ?? '')}\`).selectOption(\`${esc(d.option ?? '')}\`)`]
    case 'assert_url':
      return [`await expect(page).toHaveURL(/${esc(d.pattern ?? '')}/, { timeout: 15_000 })`]
    case 'assert_visible':
      return [`await expect(page.getByText(\`${esc(d.text ?? '')}\`)).toBeVisible()`]
    case 'assert_not_visible':
      return [`await expect(page.getByText(\`${esc(d.text ?? '')}\`)).not.toBeVisible()`]
    case 'assert_value':
      return [`await expect(page.getByPlaceholder(\`${esc(d.placeholder ?? '')}\`)).toHaveValue(\`${esc(d.value ?? '')}\`)`]
    case 'wait_ms':
      return [`await page.waitForTimeout(${d.ms ?? 1000})`]
    case 'wait_selector':
      return [`await page.getByText(\`${esc(d.text ?? '')}\`).waitFor({ timeout: 10_000 })`]
    case 'screenshot':
      return [`await page.screenshot({ path: \`test-results/${esc(d.screenshotName ?? 'screenshot')}.png\` })`]
    default:
      return [`// TODO: unsupported node type "${(d as FlowNodeData).type}"`]
  }
}

/** Escapes backtick, backslash, and ${ for use inside template literals */
function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}
