import type { TestSuite } from '@/db/schema/test_suites'
import type { Collection } from '@/db/schema/collections'
import type { Request } from '@/db/schema/requests'

export interface PlaywrightCodegenInput {
  suite: TestSuite
  collection: Collection
  requests: Request[]
  environmentName?: string
}

/**
 * Generates a Playwright TypeScript test file from a test suite configuration.
 * Variables like {{varName}} are preserved with a comment noting manual substitution.
 */
export function generatePlaywrightTest(input: PlaywrightCodegenInput): string {
  const { suite, collection, requests, environmentName } = input
  const now = new Date().toISOString()

  const dataRowsJson = JSON.stringify(suite.dataRows, null, 2)
  const hasDataRows = suite.dataRows.length > 0

  const lines: string[] = []

  lines.push(`// Generated by KayScope — Test Suite: "${suite.name}"`)
  lines.push(`// Collection: "${collection.name}"${environmentName ? ` | Environment: "${environmentName}"` : ''}`)
  lines.push(`// Generated at: ${now}`)
  lines.push(`// NOTE: Variables like {{varName}} must be substituted manually before running.`)
  lines.push(``)
  lines.push(`import { test, expect } from '@playwright/test'`)
  lines.push(``)

  if (hasDataRows) {
    lines.push(`const DATA_ROWS = ${dataRowsJson}`)
    lines.push(``)
    lines.push(`for (const [index, dataRow] of DATA_ROWS.entries()) {`)
    lines.push(`  test(\`${suite.name} — iteration \${index + 1}\`, async ({ request }) => {`)
    lines.push(`    void dataRow // available for manual variable substitution`)
    lines.push(``)
    for (const req of requests) {
      lines.push(...buildRequestSteps(req, '    '))
    }
    lines.push(`  })`)
    lines.push(`}`)
  } else {
    lines.push(`test('${suite.name}', async ({ request }) => {`)
    for (const req of requests) {
      lines.push(...buildRequestSteps(req, '  '))
    }
    lines.push(`})`)
  }

  return lines.join('\n') + '\n'
}

function buildRequestSteps(req: Request, indent: string): string[] {
  const lines: string[] = []
  const method = req.method.toLowerCase()
  const url = req.url || '/* no URL */'

  const enabledHeaders = (req.headers ?? []).filter(h => h.enabled && h.key)
  const headersObj = enabledHeaders.length > 0
    ? `{ ${enabledHeaders.map(h => `'${h.key}': '${h.value}'`).join(', ')} }`
    : null

  const hasBody = req.body && req.body.type !== 'none' && req.body.content

  // Post-request script: extract simple pm.response.to.have.status(N) assertions
  const assertions = extractStatusAssertions(req.postRequestScript ?? '')

  lines.push(``)
  lines.push(`${indent}await test.step('${req.name || req.method + ' ' + url}', async () => {`)

  if (hasBody) {
    const bodyType = req.body!.type
    if (bodyType === 'raw' || bodyType === 'json') {
      lines.push(`${indent}  const response = await request.${method}(\`${url}\`, {`)
      if (headersObj) lines.push(`${indent}    headers: ${headersObj},`)
      lines.push(`${indent}    data: \`${escapeTemplateLiteral(req.body!.content ?? '')}\`,`)
      lines.push(`${indent}  })`)
    } else {
      lines.push(`${indent}  const response = await request.${method}(\`${url}\`, {`)
      if (headersObj) lines.push(`${indent}    headers: ${headersObj},`)
      lines.push(`${indent}    // TODO: set body for type "${bodyType}"`)
      lines.push(`${indent}  })`)
    }
  } else {
    lines.push(`${indent}  const response = await request.${method}(\`${url}\`${headersObj ? `, { headers: ${headersObj} }` : ''})`)
  }

  // Add simple status assertions
  for (const status of assertions) {
    lines.push(`${indent}  expect(response.status()).toBe(${status})`)
  }

  // Emit complex post-request script as a comment
  const complexScript = getNonStatusAssertionScript(req.postRequestScript ?? '')
  if (complexScript) {
    lines.push(`${indent}  // TODO: manual assertions from post-request script:`)
    for (const scriptLine of complexScript.split('\n').slice(0, 5)) {
      lines.push(`${indent}  //   ${scriptLine}`)
    }
  }

  lines.push(`${indent}})`)

  return lines
}

// Extracts status codes from `pm.response.to.have.status(N)` patterns
function extractStatusAssertions(script: string): number[] {
  const results: number[] = []
  const re = /pm\.response\.to\.have\.status\((\d+)\)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(script)) !== null) {
    results.push(parseInt(m[1], 10))
  }
  return results
}

// Returns non-status-check script lines, for emitting as TODO comments
function getNonStatusAssertionScript(script: string): string {
  if (!script.trim()) return ''
  const simplified = script.replace(/pm\.response\.to\.have\.status\(\d+\)/g, '').trim()
  // If the script only had status checks, nothing remains
  if (!simplified || simplified.replace(/[;{}\n\s]/g, '').length < 10) return ''
  return simplified
}

function escapeTemplateLiteral(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}
